# Generated by Django 4.0.2 on 2022-03-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Username', max_length=100)),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('subject', models.CharField(help_text='Enter Subject', max_length=100)),
                ('message', models.CharField(help_text='Enter Your Message', max_length=100)),
            ],
            options={
                'db_table': 'Contact_details',
            },
        ),
    ]
