# Generated by Django 4.0.2 on 2022-03-24 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlasmaDonorsModel',
            fields=[
                ('plasma_donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('plasma_donor_name', models.CharField(help_text='Enter Your Name', max_length=100, null=True)),
                ('donor_contact_number', models.BigIntegerField(null=True)),
                ('donor_alternate_number', models.BigIntegerField(null=True)),
                ('email', models.CharField(help_text='Enter Your Email', max_length=100, null=True)),
                ('location', models.CharField(help_text='Enter Your Location', max_length=100, null=True)),
                ('blood_group', models.CharField(help_text='Select Your Blood Group', max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 11, 56, 13, 931505))),
            ],
            options={
                'db_table': 'plasma_donors',
            },
        ),
        migrations.CreateModel(
            name='RationDonorsModel',
            fields=[
                ('ration_donor_id', models.AutoField(primary_key=True, serialize=False)),
                ('ration_donor_name', models.CharField(help_text='Enter Your Name', max_length=100, null=True)),
                ('donor_contact_number', models.BigIntegerField(null=True)),
                ('donor_alternate_number', models.BigIntegerField(null=True)),
                ('email', models.CharField(help_text='Enter Your Email', max_length=100, null=True)),
                ('location', models.CharField(help_text='Enter Your Location', max_length=100, null=True)),
                ('who_you_are', models.CharField(help_text='Select Who You are', max_length=100)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 11, 56, 13, 935505))),
            ],
            options={
                'db_table': 'ration_donors',
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(help_text='Enter Username', max_length=100)),
                ('mobile', models.BigIntegerField(help_text='Enter Mobile Number')),
                ('email', models.EmailField(help_text='Enter Email', max_length=100)),
                ('location', models.CharField(help_text='Enter Location', max_length=100)),
                ('pin', models.IntegerField(help_text='Enter Mobile Number')),
                ('password', models.CharField(help_text='Enter Password', max_length=100)),
                ('profile_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'user_reg_details',
            },
        ),
        migrations.CreateModel(
            name='UserRequestModel',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter Your Name', max_length=100, null=True)),
                ('mobile', models.BigIntegerField(null=True)),
                ('alternate_mobile', models.BigIntegerField(null=True)),
                ('email', models.CharField(help_text='Enter Your Email', max_length=100, null=True)),
                ('location', models.CharField(help_text='Enter Your Location', max_length=100, null=True)),
                ('pin', models.IntegerField(null=True)),
                ('requesting_for', models.CharField(help_text='Select What you are Requesting for?', max_length=100)),
                ('message', models.TextField()),
                ('date_time', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 11, 56, 13, 936061))),
            ],
            options={
                'db_table': 'users_request',
            },
        ),
        migrations.CreateModel(
            name='UsersFeedbackModel',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(help_text='Select Your Category', max_length=100)),
                ('user_name', models.CharField(help_text='Enter Your Name', max_length=100, null=True)),
                ('user_number', models.BigIntegerField(null=True)),
                ('user_email', models.CharField(help_text='Enter Your Email', max_length=100)),
                ('feedback', models.TextField()),
                ('user_photo', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 3, 24, 11, 56, 13, 931505))),
            ],
            options={
                'db_table': 'users_feedback',
            },
        ),
    ]
